export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed-dim": "#c0c1ff",
        "background": "#f9f9f8",
        "outline-variant": "#c7c4d8",
        "surface-dim": "#dadad9",
        "on-secondary-container": "#fffbff",
        "on-surface": "#1a1c1c",
        "on-tertiary-container": "#d4dbf3",
        "surface-container": "#eeeeed",
        "surface-tint": "#4d44e3",
        "surface-container-high": "#e8e8e7",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1f0",
        "surface-bright": "#f9f9f8",
        "surface-container-low": "#f3f4f3",
        "outline": "#777587",
        "on-tertiary": "#ffffff",
        "tertiary": "#41485b",
        "secondary-container": "#6063ee",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed-dim": "#bfc6dd",
        "primary": "#3525cd",
        "surface": "#f9f9f8",
        "on-tertiary-fixed-variant": "#3f4759",
        "on-tertiary-fixed": "#141b2c",
        "surface-container-highest": "#e2e2e2",
        "primary-container": "#4f46e5",
        "secondary": "#4648d4",
        "primary-fixed-dim": "#c3c0ff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#dad7ff",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-surface-variant": "#464555",
        "tertiary-container": "#586074",
        "on-secondary-fixed": "#07006c",
        "secondary-fixed": "#e1e0ff",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed": "#dbe2fa",
        "on-background": "#1a1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "3.5rem",
        "gutter": "1.5rem",
        "space-xs": "0.375rem",
        "margin": "2rem",
        "space-lg": "2rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
